@startuml
participant "НРД" as nrd
participant "MB monitoring" as mb
participant "pl-payment-hub" as pay

== Утренний старт ==

nrd --> mb++ : Опердень за ДД.ММ.ГГГГ открыт. обмен запущен.
nrd --> pay++ : camt054
nrd --> mb : Обмен остановлен. Комментарий - мягкий старт.
pay --> mb : Метрики обработки платежей
pay--
alt Ошибок нет
    mb --> nrd : Команда на запуск обмена.
    nrd --> mb : Обмен запущен. ИД запроса такой то.
else Есть ошибки
    mb --> nrd : Подтверждающий запрос на остановку процесса.
    nrd --> mb : Обмен остановлен. ИД запроса такой то.
end alt


== Основной обмен ==

nrd --> pay++ : camt054
pay --> mb : Метрики обработки платежей
pay--
alt Возник аллерт по метрикам
    mb --> nrd : Запрос на остановку процесса.
    nrd --> mb : Обмен остановлен. ИД запроса такой то.
end alt

== Проблема решена ==

    mb --> nrd : Команда на запуск обмена.
    nrd --> mb : Обмен запущен. ИД запроса такой то.

@enduml
