@startuml

== Обработка Camt.054 ==
participant "Любой сервис" as any
participant "НРД" as nsd
participant "Личный кабинет" as lk
participant "mp-sys-rc" as rc
participant "mp-sys-bpm" as bpm
participant "mp-sys-dia" as dia

nsd -> rc : camt.054
rc ->rc : Определение платежа
alt camt.054.inbound then
    rc -> rc: реестр или нет
    alt Реестровый платеж then
        rc -> rc : учесть на регистре Реестров
        alt Есть соответствующий платежному документу реестр then
            rc -> rc : Валидация реестра
            alt rc --> od\dia : Ошибка валидации.
            end

            loop Зачисление средств на кошельки клиентов
                 rc -> rc : Учесть на свободных средтвах клиента. Internal Operation
                 rc -> bpm : Процесс учета средств по старой схеме.

            end
            rc -> dia : результат обработки реестра
        end
    else
        rc -> rc : учесть на номинальном счете.
    end
else camt.054.outbound
     rc -> rc : списать средства с НС
end

== Обратный поток из BPM ==
bpm -> rc++ : Событие движение средств по клиенту: ИД ПД, ИД клиента
rc -> rc : Учет ПД под клиентом (Зачисление на кошелек, связка с исходным ПД)
rc--


== Обработка реестров АСВ ==
dia -> rc : реестр выплат
rc -> rc : Сохранение в БД
    alt Есть соответствующий реестру платежный документ
            rc -> rc : Валидация реестра
            alt rc --> od\dia : Ошибка валидации.
            end

            loop Зачисление средств на кошельки клиентов
                 rc -> rc : Учесть на свободных средтвах клиента. Internal Operation
                 rc -> bpm : Процесс учета средств по старой схеме.
                 rc -> any : Уведомление клиента. (???)
            end
            rc -> dia : результат обработки реестра
    end

== Проверка не обработанных платежей по реестру ==

    loop В HH:mm:ss проверить наличие необработанных ПД по реестру
       alt найдены не обработанные ПД
            rc -> od : Сообщение.
       end
    end

    loop Раз в день в HH:mm:ss проверить наличие необработанных реестров с датой получение более Х дней
           alt найдены не обработанные реестры
                rc -> od : Сообщение.
           end
        end

== Возврат остатков реестра\реестра ==

dia -> bpm : Отправить остатки средств в АСВ.
bpm -> pay : Учет средств по реестру, списание...
bpm -> rc : Событие списания излишков по реестру: Сумма, ПД, ИД реестра
rc -> rc : Учет средств по реестру.
rc -> rc : Сверка платежей по реестру.
alt Сверка успешна
    rc -> rc : Закрываем реестр, ПД в финальный статус.
else
    rc -> od : Сообщение
end

@enduml
   rc -> rc : Определить заявку на внешний платеж.
    else m2m проверки пройдены, Инвойс найден
        rc->rc: учесть средства под инвойсом
        alt Инвойс пополнен полностью then
            rc -> any : Инвойс №х пополнен
        end
    else m2m проверки пройдены, инвойса нет
        rc -> rc : Учесть на свободных средтвах клиента
    else средства не определены

        rc ->rc : Учесть на невыясненных расчетах.
        alt Платеж 100% определен как не выясненный. Учету на платформе не подлежит.
            rc -> nsd : Создать возвратный платеж.
        else Платеж может принадлежать клиенту биржи\реестру.
            rc -> od : Уведомление Операционного департамента о наличии невыясненного платежа.
        end

== Создание счета на оплату ==
any -> rc : Создать инвойс
rc -> rc : Создание инвойса.
rc --> any : успех\ошибка
opt пост.обработка по инвойсу
end
== Отмена счета на оплату ==
any -> rc : Отменить инвойс
rc -> rc : Отмена инвойса.
rc --> any : успех\ошибка
opt пост.обработка по инвойсу
end


== Процесс ручного разбора невыясненного платежа ==

od -> rc++ : Запрос данных ПД
od++
return
od -> od : Ручной разбор платежа. дополнительные запросы в DevOps
alt Решение - Возврат средств. then
     rc -> nsd : Создать возвратный платеж.
else решение - Клиент определен
    alt Инвойс определен
        od -> rc : Учесть средства под инвойсом
        rc -> rc : Учет сресдтв в рамках инвойса
        rc --> od : Успех\ошибка
    else Инвойс не определен
        od -> rc : Учесть средства на кошельке клиента
        rc -> rc : Учет сресдтв в рамках клиента (свободные средства)
        rc --> od : Успех\ошибка
    end
else Решение - Платеж реестровый
    od -> rc : Учесть средства под реестр.
    rc -> rc : учесть на регистре Реестров
    rc -> rc : Запустить процесс обработки реестров.
end
od--
