@startuml
'https://plantuml.com/sequence-diagram

'autonumber
'participant "Любой сервис" as any

participant "mp-sys-dia" as dia
participant "НРД" as nsd
participant "Личный кабинет" as lk
participant "pl-payment-hub" as hub
participant "mp-sys-bpm" as bpm
participant "mp-sys-payment" as pay
participant "CRAML" as craml
== Блок поступления платежа\реестра ==
dia --> hub++ : Документ реестра
hub -> hub : Валидация реестра.
alt Валидация не пройдена
    hub -> dia : Сообщение с ошибкой.
else Валидация пройдена
    hub -> hub : Запись реестра в БД.
    hub -> hub : Поиск платежа реестра
    alt Платеж не найден
        ' Ожидаем платеж.
    else Платеж найден
        hub -> hub : Валидация платежа.
        alt Платеж не соответствует реестру на 100%.
            hub -> dia : Сообщение с ошибкой
            hub -> hub : Платеж переводится на невыясненные.
        else Платеж 100% соответствует.
            hub -> hub : Запустить процедуру обработки реестра.
        end
    end
end
nsd --> hub : Платежный документ поступление средств.
hub -> hub : Валидация платежа.
alt Валидация не пройдена
    hub -> hub : Установить инцедент.

else Валидация пройдена
    hub -> hub : Сохранить в БД с статусом "получен"
    hub -> hub : Определение принадлежности платежа.
    alt Платеж не определен.
        hub -> hub : Сохранить в БД с статусом "не определен"
        hub -> bpm++ : Отправить сообщение в исходном виде.\nРазбор платежа на стороне bpm.
        bpm -> bpm : Определение процесса платежа\n(либо базовый Replenishment, либо\nкорреляция в запущенный процесс\nожидающий платеж.)
        bpm -> pay : Учет средств на соответствующих финапах.
        bpm -> hub : Событие зеркального учета.
        bpm--
        alt Платеж учтен как невыясненный
            hub -> hub : Обработки нет. Ожидаем возврат средств.
        else Платеж зачислен на кошелек
            hub -> hub : Установить статус платежа "клиентский"
            hub -> hub : Учесть средства на кошельке клиента.
            hub -> hub : Установить статус платежа "Обработан"
        else Платеж зачислен на резерв под открытие вклада
            hub -> hub : Установить статус платежа "под счет"
            hub -> hub : Создать счет на оплату.
            hub -> hub : Учесть средства на поступлениях на счет.
            hub -> hub : Установить статус платежа "Обработан"

        end
    else Платеж определен как реестровый.
        hub -> hub : Сохранить в БД с статусом "Ожидает реестр"
        hub -> hub : Выполнить поиск соответствующего реестра на зачисление(выплату)
        alt Реестр не найден.
            hub -> hub : Установить таймер ожидания реестра.\nЕсли за заданное время (до 16.00)\nреестр по платежу не будет определен\n(платеж не будет соотнесен ни с одним реестром)\nнеобходимо отправить соответствующее событие\nв опердеп и ожидать команды на возврат средств.
        else Реестр найден.
            hub -> hub : Валидация платежа.
            alt Платеж не соответствует реестру на 100%.
                hub -> dia : Сообщение с ошибкой
                hub -> hub : Платеж переводится на невыясненные.
            else Платеж 100% соответствует.
                hub -> hub : Запустить процедуру обработки реестра.

            end
        end
    end
end
hub--
== Блок обработки реестра ==

hub->hub+ : Событие запуска обработки реестра.
loop До последней записи в реестре
    hub -> craml++ : По ИД клиента, запросить данные.
    return : Данные клиента, список проверок.
    alt Клиент не найден\клиент отклчен от платформы\не активен
        hub -> hub : Установить статус записи реестра "не успешно"
    else Клиент найден.
        hub -> hub : Учесть средства на кошельке клиента.
        hub -> bpm+: Отправить событие зеркального учета
        bpm -> pay : Учет средств на соответствующих финапах.
        return : результат обработки
        alt Успешный учет
            hub -> hub : Установить статус записи реестра "успешно"
        else Ошибка учета по старой схеме
            hub -> hub : Установить статус записи реестра "не успешно"
            hub -> hub : Установить инцедент.
        end
    end

end
@enduml