@startuml
== Параллельная обработка входящего реестрового платежа в двух учетных системах ==
nsd -> pay++ : camt.054.in
pay -> pay++ : Платеж отнесен к невыясненным.
pay--
nsd -> hub++ : camt.054.in
hub -> hub++ : Определение платежа
alt Платеж не определен.
    hub -> hub--: Payment.document.status = не выяснен.
else Платеж определен как реестровый
    hub -> hub : Реестровый платежа
    hub -> pay-- : Событие учета платежа как реестрового.
    pay -> pay : Create operation

end
pay--

== Текущий процесс возврата невыясненных ==

od -> pay : REST запрос, возврат не выясненного платежа отправителю.
pay -> nsd : pain.001
...
nsd -> pay : camt.054.out (pain.001)
pay -> pay : Create operation Списание с финапа невыясненных и с номинального счета.
nsd -> hub : camt.054.out (pain.001)
hub -> hub : Учет списания по корневому счету
pay -> hub : Зеркалирование возврата невыясненных.
hub -> hub : Создание связи между входящим и исходящим платежным документом.

== Возврат невыясненного реестрового платежа ==
od -> pay : REST запрос, возврат не выясненного платежа отправителю. Дополнительно содержит назначение платежа.
pay -> nsd : pain.001
...
nsd -> pay : camt.054.out (pain.001)
pay -> pay : Create operation списание с финапа реестров и номинального счета. (новая операция)
nsd -> hub : camt.054.out (pain.001)
hub -> hub : Учет списания по корневому счету
pay -> hub : Зеркалирование возврата невыясненных.
hub -> hub : Создание связи между входящим и исходящим платежным документом.


@enduml