@startuml

actor "источник рестра" as acc
participant "Платежный хаб" as hub
participant "НРД" as nsd

acc -> hub : Событие возврата излишков\остатка по реестру
hub -> hub : Поиск соответствующего реестра
alt реестр найден
    hub -> hub : Проверка соответствии сумме возврата и сумме остатка средств по реестру
    alt Суммы соответствуют
        hub -> hub : Проверка рабочего времени НРД
        alt Платеж можно отправить
            hub -> hub : Определение ПД связанного с реестром. Выделение реквизитов отправителя
            hub -> hub : Создание ПД в статусе новый.
            hub -> nsd : pain.001
            == обработка ответов платежной системы ==
            alt admi.002 or pain.002.RJCT
                hub -> hub : Платежный документ перевести в статус "отклонен"
                hub -> hub : Реестр - статус ошибка возврата.
                hub  --> acc : Результат обработки возврата средств. с статусом реестра.
            end
            alt camt.054
                            hub -> hub : Платежный документ перевести в статус "обработан"
                            hub -> hub : Реестр - статус Завершен.
                            hub  --> acc : Результат обработки возврата средств. с статусом реестра. + платежный документ
            end
            alt pain.002.ACSP
                            hub -> hub : Платежный документ перевести в статус "принят в обработку"
            end
            alt pain.002.PNDG
                            hub -> hub : Платежный документ перевести в статус "отложен"
            end

        else текущее время не соответствует рабочему времени НРД
            hub -> hub : Установить задержку до наступления рабочего времени.
        end
    else суммы не соответствуют
        hub -> hub : Установить статус реестра - ошибка возврата.
        hub  --> acc : Результат обработки возврата средств. с статусом реестра.
    end
else
    hub --> acc : Статус обработки возврата - реестр не найден.
end

@enduml