@startuml
skinparam linetype ortho
NEW  --> WAITING_FOR_1C
WAITING_FOR_1C --> ACCEPTED_1C
WAITING_FOR_1C --> VALIDATION_FAILED
VALIDATION_FAILED --> WAITING_FOR_1C
ACCEPTED_1C --> RECEIVED_1C
RECEIVED_1C --> OEBS
OEBS --> CREATE_ORDER
CREATE_ORDER --> NOT_ENOUGH_MONEY
NOT_ENOUGH_MONEY-->PAYMENT_CREATED
CREATE_ORDER -->PAYMENT_CREATED
PAYMENT_CREATED-->ORDER_COMPLETED
ORDER_COMPLETED--> WAITING_FOR_PAYMENT

VALIDATION_FAILED --> CANCELED
WAITING_FOR_PAYMENT --> PROCESSING
PROCESSING --> PROCESSED
PROCESSING --> WAITING_FOR_REFUND
WAITING_FOR_REFUND -->  REFUND
WAITING_FOR_REFUND --> PROCESSED
REFUND#green -->  REFUND_FAIL
REFUND -->  PROCESSED
REFUND_FAIL#green -->  WAITING_FOR_REFUND#green
@enduml