@startuml
(*) --> [Устанавливается\nпри записи реестра] NEW
NEW --> [Устанавливается\nпосле первичной\nвалидации реестра] WAITING_FOR_PAYMENT
NEW -> [Валидация\nреестра\nне пройдена] VALIDATION_FAILED
WAITING_FOR_PAYMENT --> [Реестр\nвзят в работу. ] PROCESSING
PROCESSING --> [Успешно обработан.\nСредства зачислены\n на кошелек.] PROCESSED
PROCESSING --> [Успешно обработан,\nно есть остаток\nдля возврата в АСВ.\nОжидаем информации\nдля возврата] WAITING_FOR_REFUND
PROCESSING --> [Успешно обработан,\nно есть остаток\nдля уплаты налогов\nОжидаем подтверждение\nоплаты налога] WAITING_FOR_TAX_PAID
WAITING_FOR_TAX_PAID#green-->[Платеж в налоговую\n подтвержден в НРД] TAX_PROCESSED
TAX_PROCESSED#green --> PROCESSED
WAITING_FOR_PAYMENT --> [Отклонен.\nПлатежный документ\nполучен, но\nесть ошибки.] VALIDATION_FAILED
WAITING_FOR_PAYMENT --> [В течении\nтрех дней\nне получен\nПД по реестру] ARCHIVED
WAITING_FOR_REFUND --> [Получен запрос\nна возврат.\nВыполняем.] REFUND
REFUND -> [Ошибка Возврата] REFUND_FAILED
REFUND --> [Успешный возврат] PROCESSED
REFUND_FAILED --> [Сообщение о ошибке\nвозврата передано\nв систему источник.\nОжидаем информацию\nдля возврата.] WAITING_FOR_REFUND
PROCESSED --> (*)
VALIDATION_FAILED -> (*)
ARCHIVED --> (*)
@enduml