@startuml
hide circle

entity person{
id
name
second_name
dob

}

entity contacts{
id
person_id PK
}

entity documents{
}

entity product_links

contacts }o--|| person
documents }o--|| person
product_links }o--|| person

@enduml